//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhereToStudy.vResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhereToStudy.vResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лекции.
        /// </summary>
        public static string srtLectures {
            get {
                return ResourceManager.GetString("srtLectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За нас.
        /// </summary>
        public static string strAbout {
            get {
                return ResourceManager.GetString("strAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави.
        /// </summary>
        public static string strAdd {
            get {
                return ResourceManager.GetString("strAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави курс.
        /// </summary>
        public static string strAddCourse {
            get {
                return ResourceManager.GetString("strAddCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави дисциплина.
        /// </summary>
        public static string strAddDiscipline {
            get {
                return ResourceManager.GetString("strAddDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави факултет.
        /// </summary>
        public static string strAddFacult {
            get {
                return ResourceManager.GetString("strAddFacult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави факултет.
        /// </summary>
        public static string strAddFaculty {
            get {
                return ResourceManager.GetString("strAddFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави лекция.
        /// </summary>
        public static string strAddLecture {
            get {
                return ResourceManager.GetString("strAddLecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави ново умение.
        /// </summary>
        public static string strAddNewSkill {
            get {
                return ResourceManager.GetString("strAddNewSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави специалност.
        /// </summary>
        public static string strAddSpecialty {
            get {
                return ResourceManager.GetString("strAddSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави университет.
        /// </summary>
        public static string strAddUniversity {
            get {
                return ResourceManager.GetString("strAddUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разширено търсене.
        /// </summary>
        public static string strAdvancedSearch {
            get {
                return ResourceManager.GetString("strAdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обща информация.
        /// </summary>
        public static string strAllInformation {
            get {
                return ResourceManager.GetString("strAllInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средна заплата.
        /// </summary>
        public static string strAvarageSalary {
            get {
                return ResourceManager.GetString("strAvarageSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бг.
        /// </summary>
        public static string strBulgarian {
            get {
                return ResourceManager.GetString("strBulgarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промени.
        /// </summary>
        public static string strChange {
            get {
                return ResourceManager.GetString("strChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Провери.
        /// </summary>
        public static string strCheck {
            get {
                return ResourceManager.GetString("strCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Провери къде може да се реализираш.
        /// </summary>
        public static string strCheckWhereToWork {
            get {
                return ResourceManager.GetString("strCheckWhereToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избери ... .
        /// </summary>
        public static string strChoose {
            get {
                return ResourceManager.GetString("strChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете курс от списъка:.
        /// </summary>
        public static string strChooseCourseFromList {
            get {
                return ResourceManager.GetString("strChooseCourseFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избери професия.
        /// </summary>
        public static string strChooseProfession {
            get {
                return ResourceManager.GetString("strChooseProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете университет, към който искате да добавите специалност:.
        /// </summary>
        public static string strChooseUniversityToSpec {
            get {
                return ResourceManager.GetString("strChooseUniversityToSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Град.
        /// </summary>
        public static string strCity {
            get {
                return ResourceManager.GetString("strCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдете парола..
        /// </summary>
        public static string strConfirmPassword {
            get {
                return ResourceManager.GetString("strConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакти.
        /// </summary>
        public static string strContact {
            get {
                return ResourceManager.GetString("strContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верни отговори:.
        /// </summary>
        public static string strCorrectAnswers {
            get {
                return ResourceManager.GetString("strCorrectAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Държава.
        /// </summary>
        public static string strCountry {
            get {
                return ResourceManager.GetString("strCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс : .
        /// </summary>
        public static string strCourse {
            get {
                return ResourceManager.GetString("strCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съдържание на курса.
        /// </summary>
        public static string strCourseContent {
            get {
                return ResourceManager.GetString("strCourseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на курса.
        /// </summary>
        public static string strCourseName {
            get {
                return ResourceManager.GetString("strCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсове.
        /// </summary>
        public static string strCourses {
            get {
                return ResourceManager.GetString("strCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string strDate {
            get {
                return ResourceManager.GetString("strDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрии.
        /// </summary>
        public static string strDelete {
            get {
                return ResourceManager.GetString("strDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрий специалността.
        /// </summary>
        public static string strDeleteSpecialty {
            get {
                return ResourceManager.GetString("strDeleteSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string strDescription {
            get {
                return ResourceManager.GetString("strDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дисциплина.
        /// </summary>
        public static string strDiscipline {
            get {
                return ResourceManager.GetString("strDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дисциплини.
        /// </summary>
        public static string strDisciplines {
            get {
                return ResourceManager.GetString("strDisciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирай.
        /// </summary>
        public static string strEdit {
            get {
                return ResourceManager.GetString("strEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирай курса.
        /// </summary>
        public static string strEditCourse {
            get {
                return ResourceManager.GetString("strEditCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирай специалността.
        /// </summary>
        public static string strEditSpecialty {
            get {
                return ResourceManager.GetString("strEditSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма на обучението.
        /// </summary>
        public static string strEducationForm {
            get {
                return ResourceManager.GetString("strEducationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Език на преподаване.
        /// </summary>
        public static string strEducationLanguage {
            get {
                return ResourceManager.GetString("strEducationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна система за обучение.
        /// </summary>
        public static string strELearningSystem {
            get {
                return ResourceManager.GetString("strELearningSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анг.
        /// </summary>
        public static string strEnglish {
            get {
                return ResourceManager.GetString("strEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете описание на специалността.
        /// </summary>
        public static string strEnterSpecialtyDescription {
            get {
                return ResourceManager.GetString("strEnterSpecialtyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете информация за специалността.
        /// </summary>
        public static string strEnterSpecialtyInformation {
            get {
                return ResourceManager.GetString("strEnterSpecialtyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        public static string strExit {
            get {
                return ResourceManager.GetString("strExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факултети.
        /// </summary>
        public static string strFaculties {
            get {
                return ResourceManager.GetString("strFaculties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факултет.
        /// </summary>
        public static string strFaculty {
            get {
                return ResourceManager.GetString("strFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Филтрирай.
        /// </summary>
        public static string strFilter {
            get {
                return ResourceManager.GetString("strFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За нас.
        /// </summary>
        public static string strForUs {
            get {
                return ResourceManager.GetString("strForUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име и фамилия.
        /// </summary>
        public static string strFullName {
            get {
                return ResourceManager.GetString("strFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте, .
        /// </summary>
        public static string strHello {
            get {
                return ResourceManager.GetString("strHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string strHome {
            get {
                return ResourceManager.GetString("strHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string strInformation {
            get {
                return ResourceManager.GetString("strInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това е електронна система за обучение. В нея са включени различни обучителни курсове и съответните им лекции..
        /// </summary>
        public static string strInformationAbout {
            get {
                return ResourceManager.GetString("strInformationAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to След преминаването на даден материал може да тествате знанията си в раздел &quot;Тестове&quot;..
        /// </summary>
        public static string strInformationAbout2 {
            get {
                return ResourceManager.GetString("strInformationAbout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системата ви позволява да се обучавате в различни сфери. Може да избереш най-подходящия курс за теб и да започнеш веднага..
        /// </summary>
        public static string strInformationHome {
            get {
                return ResourceManager.GetString("strInformationHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сте избрали към кой курс искате да участвате? Прегледате всички курсове с възможните им лекции. Можете лесно да го направите от тук..
        /// </summary>
        public static string strInformationHome2 {
            get {
                return ResourceManager.GetString("strInformationHome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете кратко описание на курса.
        /// </summary>
        public static string strInsertCourseDescription {
            get {
                return ResourceManager.GetString("strInsertCourseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете съдържанието на лекцията.
        /// </summary>
        public static string strInsertLectureDescription {
            get {
                return ResourceManager.GetString("strInsertLectureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Професия.
        /// </summary>
        public static string strJob {
            get {
                return ResourceManager.GetString("strJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Език.
        /// </summary>
        public static string strLanguage {
            get {
                return ResourceManager.GetString("strLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Език на преподаване.
        /// </summary>
        public static string strLanguageEducation {
            get {
                return ResourceManager.GetString("strLanguageEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Научи повече.
        /// </summary>
        public static string strLearnMore {
            get {
                return ResourceManager.GetString("strLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чудиш се коя специалност е подходяща за теб? Въведи свойте изисквания и виж коя отговаря на тях..
        /// </summary>
        public static string strLearnMore1Text {
            get {
                return ResourceManager.GetString("strLearnMore1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разгледай тук университетите и избери..
        /// </summary>
        public static string strLearnMoreText {
            get {
                return ResourceManager.GetString("strLearnMoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съдържание на лекцията.
        /// </summary>
        public static string strLectureDescription {
            get {
                return ResourceManager.GetString("strLectureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на лекцията.
        /// </summary>
        public static string strLectureName {
            get {
                return ResourceManager.GetString("strLectureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лекции.
        /// </summary>
        public static string strLectures {
            get {
                return ResourceManager.GetString("strLectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списък с лекции.
        /// </summary>
        public static string strListOfLectures {
            get {
                return ResourceManager.GetString("strListOfLectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списък със специалностите.
        /// </summary>
        public static string strListSpecialties {
            get {
                return ResourceManager.GetString("strListSpecialties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string strLogin {
            get {
                return ResourceManager.GetString("strLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейл.
        /// </summary>
        public static string strMail {
            get {
                return ResourceManager.GetString("strMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моят избор.
        /// </summary>
        public static string strMyChoice {
            get {
                return ResourceManager.GetString("strMyChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моят профил.
        /// </summary>
        public static string strMyProfile {
            get {
                return ResourceManager.GetString("strMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОКС.
        /// </summary>
        public static string strOks {
            get {
                return ResourceManager.GetString("strOks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string strPassword {
            get {
                return ResourceManager.GetString("strPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сте въвели парола..
        /// </summary>
        public static string strPasswordError {
            get {
                return ResourceManager.GetString("strPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата трябва да е минимум 5 символа.
        /// </summary>
        public static string strPasswordLengthValidation {
            get {
                return ResourceManager.GetString("strPasswordLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възможности.
        /// </summary>
        public static string strPossibilities {
            get {
                return ResourceManager.GetString("strPossibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процент:.
        /// </summary>
        public static string strProcent {
            get {
                return ResourceManager.GetString("strProcent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влез в профила си.
        /// </summary>
        public static string strProfileLogin {
            get {
                return ResourceManager.GetString("strProfileLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класация.
        /// </summary>
        public static string strRang {
            get {
                return ResourceManager.GetString("strRang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрирай.
        /// </summary>
        public static string strRegister {
            get {
                return ResourceManager.GetString("strRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрирай се като нов потребител.
        /// </summary>
        public static string strRegisterAsNewUser {
            get {
                return ResourceManager.GetString("strRegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string strRegistration {
            get {
                return ResourceManager.GetString("strRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резултати.
        /// </summary>
        public static string strResults {
            get {
                return ResourceManager.GetString("strResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запази.
        /// </summary>
        public static string strSave {
            get {
                return ResourceManager.GetString("strSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсене.
        /// </summary>
        public static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потърсете желаната от вас специалност.
        /// </summary>
        public static string strSearchDesiredSpecialty {
            get {
                return ResourceManager.GetString("strSearchDesiredSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потърси университет....
        /// </summary>
        public static string strSearchUniversity {
            get {
                return ResourceManager.GetString("strSearchUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Семестър.
        /// </summary>
        public static string strSemester {
            get {
                return ResourceManager.GetString("strSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Семестриална такса.
        /// </summary>
        public static string strSemTax {
            get {
                return ResourceManager.GetString("strSemTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Умение.
        /// </summary>
        public static string strSkill {
            get {
                return ResourceManager.GetString("strSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Умения.
        /// </summary>
        public static string strSkills {
            get {
                return ResourceManager.GetString("strSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортирай по : .
        /// </summary>
        public static string strSortBy {
            get {
                return ResourceManager.GetString("strSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специалности.
        /// </summary>
        public static string strSpecialties {
            get {
                return ResourceManager.GetString("strSpecialties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специалност.
        /// </summary>
        public static string strSpecialty {
            get {
                return ResourceManager.GetString("strSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли за специалността:.
        /// </summary>
        public static string strSpecialtyDetails {
            get {
                return ResourceManager.GetString("strSpecialtyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Започнете.
        /// </summary>
        public static string strStart {
            get {
                return ResourceManager.GetString("strStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предмет.
        /// </summary>
        public static string strSubject {
            get {
                return ResourceManager.GetString("strSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система за анализ профил обучение.
        /// </summary>
        public static string strSystemTrainingProfile {
            get {
                return ResourceManager.GetString("strSystemTrainingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такса.
        /// </summary>
        public static string strTax {
            get {
                return ResourceManager.GetString("strTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест.
        /// </summary>
        public static string strTest {
            get {
                return ResourceManager.GetString("strTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестове.
        /// </summary>
        public static string strTests {
            get {
                return ResourceManager.GetString("strTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма на обучение.
        /// </summary>
        public static string strTypeEducation {
            get {
                return ResourceManager.GetString("strTypeEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Университети.
        /// </summary>
        public static string strUniversities {
            get {
                return ResourceManager.GetString("strUniversities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Университет.
        /// </summary>
        public static string strUniversity {
            get {
                return ResourceManager.GetString("strUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редакция на факултет.
        /// </summary>
        public static string strUniversityEdit {
            get {
                return ResourceManager.GetString("strUniversityEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете информация за университета.
        /// </summary>
        public static string strUniversityInformation {
            get {
                return ResourceManager.GetString("strUniversityInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        public static string strUserName {
            get {
                return ResourceManager.GetString("strUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сте въвели потребителско име..
        /// </summary>
        public static string strUserNameError {
            get {
                return ResourceManager.GetString("strUserNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед.
        /// </summary>
        public static string strView {
            get {
                return ResourceManager.GetString("strView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добре дошли в електронната система за обучение и тестове.
        /// </summary>
        public static string strWelcome {
            get {
                return ResourceManager.GetString("strWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешни отговори:.
        /// </summary>
        public static string strWrongAnswers {
            get {
                return ResourceManager.GetString("strWrongAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителското име и/или паролата е грешно..
        /// </summary>
        public static string strWrongUserNameOrPassword {
            get {
                return ResourceManager.GetString("strWrongUserNameOrPassword", resourceCulture);
            }
        }
    }
}
