//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhereToStudy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhereToStudy.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лекции.
        /// </summary>
        internal static string srtLectures {
            get {
                return ResourceManager.GetString("srtLectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За нас.
        /// </summary>
        internal static string strAbout {
            get {
                return ResourceManager.GetString("strAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави.
        /// </summary>
        internal static string strAdd {
            get {
                return ResourceManager.GetString("strAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави курс.
        /// </summary>
        internal static string strAddCourse {
            get {
                return ResourceManager.GetString("strAddCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави лекция.
        /// </summary>
        internal static string strAddLecture {
            get {
                return ResourceManager.GetString("strAddLecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бг.
        /// </summary>
        internal static string strBulgarian {
            get {
                return ResourceManager.GetString("strBulgarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Провери.
        /// </summary>
        internal static string strCheck {
            get {
                return ResourceManager.GetString("strCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете курс от списъка:.
        /// </summary>
        internal static string strChooseCourseFromList {
            get {
                return ResourceManager.GetString("strChooseCourseFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдете парола..
        /// </summary>
        internal static string strConfirmPassword {
            get {
                return ResourceManager.GetString("strConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакти.
        /// </summary>
        internal static string strContact {
            get {
                return ResourceManager.GetString("strContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верни отговори:.
        /// </summary>
        internal static string strCorrectAnswers {
            get {
                return ResourceManager.GetString("strCorrectAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс : .
        /// </summary>
        internal static string strCourse {
            get {
                return ResourceManager.GetString("strCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съдържание на курса.
        /// </summary>
        internal static string strCourseContent {
            get {
                return ResourceManager.GetString("strCourseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на курса.
        /// </summary>
        internal static string strCourseName {
            get {
                return ResourceManager.GetString("strCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсове.
        /// </summary>
        internal static string strCourses {
            get {
                return ResourceManager.GetString("strCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string strDate {
            get {
                return ResourceManager.GetString("strDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрии.
        /// </summary>
        internal static string strDelete {
            get {
                return ResourceManager.GetString("strDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирай.
        /// </summary>
        internal static string strEdit {
            get {
                return ResourceManager.GetString("strEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирай курса.
        /// </summary>
        internal static string strEditCourse {
            get {
                return ResourceManager.GetString("strEditCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирай лекцията.
        /// </summary>
        internal static string strEditLecture {
            get {
                return ResourceManager.GetString("strEditLecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна система за обучение.
        /// </summary>
        internal static string strELearningSystem {
            get {
                return ResourceManager.GetString("strELearningSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Непопълнени отговори:.
        /// </summary>
        internal static string strEmptyAnswers {
            get {
                return ResourceManager.GetString("strEmptyAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анг.
        /// </summary>
        internal static string strEnglish {
            get {
                return ResourceManager.GetString("strEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        internal static string strExit {
            get {
                return ResourceManager.GetString("strExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За нас.
        /// </summary>
        internal static string strForUs {
            get {
                return ResourceManager.GetString("strForUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име и фамилия.
        /// </summary>
        internal static string strFullName {
            get {
                return ResourceManager.GetString("strFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценка:.
        /// </summary>
        internal static string strGrade {
            get {
                return ResourceManager.GetString("strGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте, .
        /// </summary>
        internal static string strHello {
            get {
                return ResourceManager.GetString("strHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        internal static string strHome {
            get {
                return ResourceManager.GetString("strHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това е електронна система за обучение. В нея са включени различни обучителни курсове и съответните им лекции..
        /// </summary>
        internal static string strInformationAbout {
            get {
                return ResourceManager.GetString("strInformationAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to След преминаването на даден материал може да тествате знанията си в раздел &quot;Тестове&quot;..
        /// </summary>
        internal static string strInformationAbout2 {
            get {
                return ResourceManager.GetString("strInformationAbout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системата ви позволява да се обучавате в различни сфери. Може да избереш най-подходящия курс за теб и да започнеш веднага..
        /// </summary>
        internal static string strInformationHome {
            get {
                return ResourceManager.GetString("strInformationHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сте избрали към кой курс искате да участвате? Прегледате всички курсове с възможните им лекции. Можете лесно да го направите от тук..
        /// </summary>
        internal static string strInformationHome2 {
            get {
                return ResourceManager.GetString("strInformationHome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете кратко описание на курса.
        /// </summary>
        internal static string strInsertCourseDescription {
            get {
                return ResourceManager.GetString("strInsertCourseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете съдържанието на лекцията.
        /// </summary>
        internal static string strInsertLectureDescription {
            get {
                return ResourceManager.GetString("strInsertLectureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Научи повече.
        /// </summary>
        internal static string strLearnMore {
            get {
                return ResourceManager.GetString("strLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съдържание на лекцията.
        /// </summary>
        internal static string strLectureDescription {
            get {
                return ResourceManager.GetString("strLectureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на лекцията.
        /// </summary>
        internal static string strLectureName {
            get {
                return ResourceManager.GetString("strLectureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лекции.
        /// </summary>
        internal static string strLectures {
            get {
                return ResourceManager.GetString("strLectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списък с лекции.
        /// </summary>
        internal static string strListOfLectures {
            get {
                return ResourceManager.GetString("strListOfLectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string strLogin {
            get {
                return ResourceManager.GetString("strLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейл.
        /// </summary>
        internal static string strMail {
            get {
                return ResourceManager.GetString("strMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        internal static string strPassword {
            get {
                return ResourceManager.GetString("strPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сте въвели парола..
        /// </summary>
        internal static string strPasswordError {
            get {
                return ResourceManager.GetString("strPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата трябва да е минимум 5 символа.
        /// </summary>
        internal static string strPasswordLengthValidation {
            get {
                return ResourceManager.GetString("strPasswordLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възможности.
        /// </summary>
        internal static string strPossibilities {
            get {
                return ResourceManager.GetString("strPossibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процент:.
        /// </summary>
        internal static string strProcent {
            get {
                return ResourceManager.GetString("strProcent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влез в профила си.
        /// </summary>
        internal static string strProfileLogin {
            get {
                return ResourceManager.GetString("strProfileLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрирай.
        /// </summary>
        internal static string strRegister {
            get {
                return ResourceManager.GetString("strRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        internal static string strRegistration {
            get {
                return ResourceManager.GetString("strRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резултати.
        /// </summary>
        internal static string strResults {
            get {
                return ResourceManager.GetString("strResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запази.
        /// </summary>
        internal static string strSave {
            get {
                return ResourceManager.GetString("strSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортирай по : .
        /// </summary>
        internal static string strSortBy {
            get {
                return ResourceManager.GetString("strSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Започнете.
        /// </summary>
        internal static string strStart {
            get {
                return ResourceManager.GetString("strStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест.
        /// </summary>
        internal static string strTest {
            get {
                return ResourceManager.GetString("strTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестове.
        /// </summary>
        internal static string strTests {
            get {
                return ResourceManager.GetString("strTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        internal static string strUserName {
            get {
                return ResourceManager.GetString("strUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сте въвели потребителско име..
        /// </summary>
        internal static string strUserNameError {
            get {
                return ResourceManager.GetString("strUserNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добре дошли в електронната система за обучение и тестове.
        /// </summary>
        internal static string strWelcome {
            get {
                return ResourceManager.GetString("strWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешни отговори:.
        /// </summary>
        internal static string strWrongAnswers {
            get {
                return ResourceManager.GetString("strWrongAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителското име и/или паролата е грешно..
        /// </summary>
        internal static string strWrongUserNameOrPassword {
            get {
                return ResourceManager.GetString("strWrongUserNameOrPassword", resourceCulture);
            }
        }
    }
}
